### ISSUE TITLE
Information main category column empty

### ISSUE THREAD

**Issue by yvonn** [optimlab/optimblog#1]
In backend when open catalog/information the categories are not displayed in column Main Category. Only in your demo it is ok.

**Comment by yvonn** [comment]
Same with product list

**Comment by yvonn** [comment]
I had it fixed now it works. It need some changes in OptimBlog - admin: Filter Categories, Products and Informations xml file

**Comment by yvonn** [comment]
I added install.xml file as zip. 
[optimblog-admin-filter-cat-prod-info.ocmod.zip](https://github.com/optimlab/optimblog/files/3033873/optimblog-admin-filter-cat-prod-info.ocmod.zip)

**Comment by optimlab** [comment]
The Main Category column displays only the Main categories that are needed to form breadcrumbs.
To see the secondary categories, use the filter. It will display all articles and products belonging to a particular category.
