### ISSUE TITLE
Popup calendar

### ISSUE THREAD

**Issue by mmojadad** [optimlab/optimblog#13]
In information tab of information, In Date Added/Date Available/Date End popup calendar not load in my side, The pop up calendar in all other areas of my OC for example Date/Time files of Options working correctly.

**Comment by optimlab** [comment]
Which version opencart?

**Comment by mmojadad** [comment]
3.0.2

**Comment by optimlab** [comment]
Not confirmed.
It works perfectly on the native Opencart 3.
