### ISSUE TITLE
Double

### ISSUE THREAD

**Issue by mmojadad** [optimlab/optimblog#16]
On latest build i face the following issue :
When i create an article, Some elements ( Slideshow, Reviews, Related Articles, Related Products ) show double on front-end. 
All other features working fine in latest build.

**Comment by optimlab** [comment]
Why did the modification work on your site 2 times?

**Comment by mmojadad** [comment]
> 
> 
> Why did the modification work on your site 2 times?

Yes, I checked modification and notice there is 2 instance of OptimBlog, 
1. OptimBlog
2. OptimBlog - All Theme
Disabled the first one and rebuild modification fix it for me. Now show in normal way.
