### ISSUE TITLE
Manage Articles review's

### ISSUE THREAD

**Issue by mmojadad** [optimlab/optimblog#18]
In admin area, Review moderation for articles not show. In front-end review submit correctly.

**Comment by optimlab** [comment]
![OptimBlog-14](https://user-images.githubusercontent.com/20772662/84170040-f53adc80-aa81-11ea-8cd3-92967c750f38.png)

**Comment by mmojadad** [comment]
> 
> 
> ![OptimBlog-14](https://user-images.githubusercontent.com/20772662/84170040-f53adc80-aa81-11ea-8cd3-92967c750f38.png)

Yes, Exactly! On previews version i had it there, But in latest version this items do not show for me.
OptimBlog - All Theme is active ( OptimBlog is inactive )

**Comment by optimlab** [comment]
Because the main module cannot be disabled! You must change the path for your template name (`catalog/view/theme/*/template` -> `catalog/view/theme/theme_name/template`) in the modification `optimblog-all-theme-twig.ocmod`.
And archive in **.zip** again.

**Comment by mmojadad** [comment]
> 
> 
> Because the main module cannot be disabled! You must change the path for your template name (`catalog/view/theme/*/template` -> `catalog/view/theme/theme_name/template`) in the modification `optimblog-all-theme-twig.ocmod`.
> And archive in **.zip** again.

Yes! I re-enabled the main OptimBlog, Then changed * to my theme_name and fixed now.
