### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by mmojadad** [optimlab/optimblog#20]
How could i change date show format on articles page 13.06.2018 to 13/06/2018

**Comment by optimlab** [comment]
https://www.php.net/manual/en/function.date.php
Add varible: **d/m/Y**
![Screenshot_2020-06-14 Language Editor](https://user-images.githubusercontent.com/20772662/84594343-38b69180-ae5a-11ea-9380-d006cdb3d839.png)

**Comment by mmojadad** [comment]
Yes, Worked!
