### ISSUE TITLE
Support other themes than default

### ISSUE THREAD

**Issue by a-v-l** [optimlab/optimblog#25]
It took me a couple minutes to find out why the images, related articles and products didn't show up on the article-page: the modifications made by `install.xml` only cover the default theme.

Could you please change those lines containing

> <file path="catalog/view/theme/**default**/template/…

to

> <file path="catalog/view/theme/**\***/template/…

Thank you anyway for this cool extension and all the time and work you put in the development!

**Comment by optimlab** [comment]
Forgot to write a translation of the instructions in English)))
### Adaptation to your theme:

If your theme differs from the default theme, then you need to create an additional modification. The modification [optimblog-all-theme-twig.ocmod.zip](https://github.com/optimlab/optimblog/blob/master/dist/optimblog-modification/optimblog-all-theme-twig.ocmod.zip) was created to help. Download, unzip and edit the optimblog-all-theme-twig.ocmod.zip modifier to fit your theme, replacing the path to the theme in the modification code 
from 
`catalog/view/theme/*/` 
to 
`catalog/view/theme/theme_name/`

And then re-zip it under the name **optimblog-theme-name.ocmod.zip**. If it didn’t help or didn’t help completely, then you need to figure it out by fixing it or order an adaptation for your template. You also need to know that the article category template is located at [catalog/view/theme/default/template/information/category.twig](https://github.com/optimlab/optimblog/blob/master/src/optimblog.ocmod/upload/catalog/view/theme/default/template/information/category.twig).

**Comment by optimlab** [comment]
In the future version I will try to make an automatic creation of an adaptation for a theme, right from the module during settings. No time now.

**Comment by a-v-l** [comment]
Thank you for the information. The differences between https://github.com/optimlab/optimblog/blob/master/src/optimblog.ocmod/install.xml and https://github.com/optimlab/optimblog/blob/master/src/optimblog-all-theme-twig.ocmod/install.xml is just the asterisk (*) and the _default_. But probably it is saver not to seach-and-replace in unknown theme files.

**Comment by optimlab** [comment]
> But probably it is saver not to seach-and-replace in unknown theme files.

And so it was at the very beginning. But it turned out to be a bad way due to conflicts on various theme. This created more problems.
