### ISSUE TITLE
Article's Image not saved

### ISSUE THREAD

**Issue by CDS-IT** [optimlab/optimblog#28]
Hello,
I have a small issue with OptimBlog.
It is working fine but recently I have problem that if I try to create a new article, and then try to add an image (Tab image of the article not in the text) it select the image, then I save the article but the image is not saved and the image doesn't show in the Category list.
I have checked the permissions in System > Users > User group
I have tried to reinstall but still same.
Cleared the cache
Opencart Version 3.0.3.6
OptimBlog V. 3.1.0.1
I'm using a custom Theme, I have generated and installed the optimblog-mytheme-theme.ocmod.zip 
Any help will be appreciated.
Thank you
Ciro

**Comment by optimlab** [comment]
I couldn't repeat your issue.
