### ISSUE TITLE
Optimblog on front page?

### ISSUE THREAD

**Issue by rvegting** [optimlab/optimblog#29]
Hello,

How can I display articles on the front page of my shop?

Thank you!

**Comment by optimlab** [comment]
Just like other modules in Opencart.

**Comment by rvegting** [comment]
Hi Dmitriy,

 

Thank you for your reply. I have tried, but it doesn’t show up… what am I doing wrong?

 

Kind Regards,

 

Remco

 

 

Van: Dmitriy Khokhlov ***@***.***> 
Verzonden: vrijdag 6 januari 2023 14:29
Aan: optimlab/optimblog ***@***.***>
CC: Remco Vegting ***@***.***>; Author ***@***.***>
Onderwerp: Re: [optimlab/optimblog] Optimblog on front page? (Issue #29)

 

Just like other modules in Opencart.

**Comment by optimlab** [comment]
What module do you want to display?

**Comment by rvegting** [comment]
I would like to display the latest article(s) on the front page if possible

 

Van: Dmitriy Khokhlov ***@***.***> 
Verzonden: zondag 8 januari 2023 16:08
Aan: optimlab/optimblog ***@***.***>
CC: Remco Vegting ***@***.***>; Author ***@***.***>
Onderwerp: Re: [optimlab/optimblog] Optimblog on front page? (Issue #29)

 

What module do you want to display?

**Comment by optimlab** [comment]
This is not a topic for discussion.Continue here:https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=34363

**Comment by optimlab** [comment]
This is not a topic for discussion.
Continue here: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=34363
