### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mauphung** [optimlab/optimblog#4]
Hi,
Is there any body already install and use this module?
Please give some note on how to install, order of modules to be installed and how to use it.
Thanks

**Comment by optimlab** [comment]
Coming soon in the next few days. After the release 3.0.1.0

**Comment by mauphung** [comment]
Is there any bug to be fixed in release 3.0.0.8?

**Comment by mauphung** [comment]
Do I have to install the following modules in this order?
1. optimblog.ocmod.zip. 
2. breadcrumb-last.ocmod.zip
3. canonical-category.ocmod.zip
4. canonical-category-no-page.ocmod.zip
5. canonical-information.ocmod.zip
6. optimblog-module-bestseller-information.ocmod.zip 
7. optimblog-module-featured-information.ocmod.zip
8. optimblog-module-latest-information.ocmod.zip
9. optimblog-module-category-information.ocmod.zip
10. optimblog-module-search-information.ocmod.zip

**Comment by mauphung** [comment]
After installing these modules I attache 3 modules at Content Top of Home Layout:

Layout > Home Content Top
Best Information		> Popular Articles
Featured Information	> Recommended Reading
Latest Information		> News
They are displayed on home page but with the links of the default Information of Opencart.
How do I add the content of module news?

**Comment by optimlab** [comment]
1. Create a category of articles - News.
2. Create articles (Information), add a category in the settings.
3. Select category in the settings Information module.

**Comment by optimlab** [comment]
Why did you create a chat here?
I left this issue open so as not to forget to write the instructions.

**Comment by mauphung** [comment]
Yes I will do. I'm a new inOpencart. I'm learning your module. It's
promising.
Thank you very much.

**Comment by optimlab** [comment]
https://github.com/optimlab/optimblog#install-instructions
