### ISSUE TITLE
OptimBlog : Latest Information

### ISSUE THREAD

**Issue by mmojadad** [optimlab/optimblog#5]
Environment : OC version 3.0.2
Issue: OptimBlog : Latest Information
When i set Limit to for example 2, Still show 4 latest blog. Also Width/Height not change correctly. But all other parameters change work fine.

**Comment by optimlab** [comment]
The module has been checked many times and works correctly. Look for the error on your site.
I suspect that you haven't updated the modification cache or cache twig.

**Comment by mmojadad** [comment]
> 
> 
> The module has been checked many times and works correctly. Look for the error on your site.
> I suspect that you haven't updated the modification cache or cache twig.

I cleared full cache , I issue is related to compatibility with other OC themes 
I am using BigShop Theme
Demo ( http://demo.harnishdesign.net/opencart/bigshop/v1/index.php?route=common/home )
In OptimBlog : Latest Information , When i change Width/Height , Nothing change in frontend.
I noticed if in my css theme change col-lg-3 from %25 to for example %35 it will show good.

**Comment by optimlab** [comment]
If there is an error in the template, what does the module have to do with it?
