### ISSUE TITLE
Not showing articles in Category

### ISSUE THREAD

**Issue by mmojadad** [optimlab/optimblog#6]
In module-category-information ( sidebar that i created in homepage ) show there is 1 article in my created category ( i created an article and assigned it to the category ), But when i visit there category message me "your shopping cart is empty" . 

http://mydomain.com/index.php?route=product/category&path=60

**Comment by optimlab** [comment]
In addition to replacing **h2** with **h1**, in the category template, the modification only clings to one line
`{% if not categories and not products %}`
finds it and changes it to the article output code.
https://github.com/optimlab/optimblog/blob/3.0.1.0_b/src/optimblog.ocmod/install.xml#L5365

I suspect that you don't have this line or you haven't updated the modification cache or cache twig.

**Comment by mmojadad** [comment]
I did not get your mean "In addition to replacing h2 with h1" , Would you please explain more?
Cache is cleared also "{% if not categories and not products %}" is exist.

**Comment by optimlab** [comment]
> I did not get your mean "In addition to replacing h2 with h1" , Would you please explain more?

https://github.com/optimlab/optimblog/blob/3.0.1.0_b/src/optimblog.ocmod/install.xml#L5360
Does this line mean anything to you?

**Comment by mmojadad** [comment]
> 
> 
> > I did not get your mean "In addition to replacing h2 with h1" , Would you please explain more?
> 
> https://github.com/optimlab/optimblog/blob/3.0.1.0_b/src/optimblog.ocmod/install.xml#L5360
> Does this line mean anything to you?

Hi
Yes and thanks for your support also your good idea and job to develop such addon. I found the issue, It was not because of h1/h2 tags in install.xml
I am using BigShop Theme
Demo ( http://demo.harnishdesign.net/opencart/bigshop/v1/index.php?route=common/home )
And noticed small issue in theme address in install.xml of optimblog.ocmod
I changed /theme/default/  to /theme/*/  and then articles in category show correctly.

**Comment by optimlab** [comment]
> I am using BigShop Theme

https://github.com/optimlab/optimblog/tree/master/src/optimblog-category-theme-all.ocmod
In the evening, I will post the version from 3.0.1.0

**Comment by mmojadad** [comment]
I noticed another issue with OptimBlog : Latest Information Width/Height , Write it here or create a new ticket?
