### ISSUE TITLE
Author

### ISSUE THREAD

**Issue by mmojadad** [optimlab/optimblog#8]
This is not an issue , Its a wish and need your guide 
I prefer to show, " Name, Family " of OC user as author of article, How is it possible?

**Comment by optimlab** [comment]
What prevents you from creating a user login "Name, Family"?

**Comment by mmojadad** [comment]
> What prevents you from creating a user login "Name, Family"?

My native language. I have to use English as login(user) name

**Comment by mmojadad** [comment]
What will be the solution?

**Comment by optimlab** [comment]
1. Add User
2. Select this user as the author
3. Keep it up

Example:
http://demo.optimcart.com/admin/index.php?route=user/user/edit&user_id=4
http://demo.optimcart.com/admin/index.php?route=catalog/information/edit&information_id=13
http://demo.optimcart.com/index.php?route=information/information&information_id=13

**Comment by mmojadad** [comment]
> 
> 
>     1. Add User
> 
>     2. Select this user as the author
> 
>     3. Keep it up
> 
> 
> Example:
> http://demo.optimcart.com/admin/index.php?route=user/user/edit&user_id=4
> http://demo.optimcart.com/admin/index.php?route=catalog/information/edit&information_id=13
> http://demo.optimcart.com/index.php?route=information/information&information_id=13

Worked!
